### ISSUE TITLE
Wondering about bower name

### ISSUE THREAD

**Issue by bevacqua** [realmike33/angular-dragula#2]
Hey there, I'm the author of `dragula`. I was wondering if you'd be willing to give up the `angular-dragula` module registration on Bower. There's now an official [`angular-dragula`](https://github.com/bevacqua/angular-dragula) package.

**Comment by realmike33** [comment]
Hi Bevacqua,

Initially, I created this repo thinking dragula wasn't going to make it's way to Angular and wanted to help out those who were searching for something quick and easy to setup. I haven't had much time to build anything on top of it this current build but Im starting to get back into working on some of my old personal projects and would like to continue working and releasing this one. 

With this said, I'll release the package name from Bower later today. 

Best of luck!

**Comment by bevacqua** [comment]
When you do, if you could, please do `bower register angular-dragula https://github.com/bevacqua/angular-dragula.git`.

:ok_hand: 

Also, many thanks!!

**Comment by bevacqua** [comment]
And of course you're more than welcome to contribute on the official one :rocket:

**Comment by realmike33** [comment]
Done. 

Yeah, I will definitely be checking out the official one.

**Comment by bevacqua** [comment]
Cool. Thanks!
